### ISSUE TITLE
Window effects shadow borders of inactive windows look weird

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/dde-kwin#115]
I don't know, what is triggering it, but at some point, window borders of inactive windows start to look like this:

![image](https://user-images.githubusercontent.com/6298761/67273323-81ca6780-f4be-11e9-9ad2-2b6dfbfed484.png)

![image](https://user-images.githubusercontent.com/6298761/67273373-99a1eb80-f4be-11e9-979f-616d34a3e441.png)

After re-login it is back to normal.

**Comment by xmuli** [comment]
@felixonmars ok

**Comment by zmj1010** [comment]
The new version of the system does not have this problem, it is recommended that you upgrade your version

> 我不知道是什么触发了它，但是在某些时候，非活动窗口的窗口边框开始看起来像这样：
> 
> ![图片](https://user-images.githubusercontent.com/6298761/67273323-81ca6780-f4be-11e9-9ad2-2b6dfbfed484.png)
> 
> ![图片](https://user-images.githubusercontent.com/6298761/67273373-99a1eb80-f4be-11e9-979f-616d34a3e441.png)
> 
> 重新登录后，它恢复正常。

**Comment by xmuli** [comment]
@zmj1010 This is a kwin problem (csy previously said that it will be fixed later), the big black side, it will take a while to use the problem, but after the execution of killall kwin_x11, it will be better again, so do not close this problem temporarily (because Not resolved)

**Comment by openarun** [comment]
@xmuli Any update with a fix for this issue ? Its present in UbuntuDDE also.

**Comment by openarun** [comment]
Hi @xmuli did you get a chance to have a look over this issue and a potential fix ?

**Comment by sonald** [comment]
this is a problem of kwin, we have fixed this in deepin fork of kwin. we'll try to submit to upstream kwin.

**Comment by xmuli** [comment]
> 嗨，@ xmuli，您是否有机会了解此问题和可能的解决方法？

I'm sorry, this problem persists, This may not be fixed until someone from dede-kwin fixes it (in arch, etc.).

**Comment by openarun** [comment]
Hi @sonald @xmuli, Thank you very much for your response. When will the patch be submitted to the upstream?

**Comment by xmuli** [comment]
> When will the patch be submitted to the upstream?

So far, no patch has appeared yet.

**Comment by bear-bulloff** [comment]
After yesterday's update, kwin finally stopped working. Effects are not included.(arch deepin, manjaro deepin)

**Comment by xmuli** [comment]
I was told today, good news. **This issue has been fixed** and is currently being verified.    [cd081ff](https://github.com/linuxdeepin/deepin-kwin/commit/cd081ff7407bf60c74febf848685c091a6432f1e)

**Comment by xmuli** [comment]
Fix black border bug when switching between 2D/3D modes.  [cd081ff](https://github.com/linuxdeepin/deepin-kwin/commit/cd081ff7407bf60c74febf848685c091a6432f1e)
